apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    app: demo-django
data:
  # Configuración de Django
  DJANGO_SETTINGS_MODULE: "demo.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
  
  # Localización
  TIME_ZONE: "America/Tegucigalpa"
  LANGUAGE_CODE: "es-hn"
  
  # Integración con SQLite (Necesario para el volumen)
  DATABASE_URL: "/app/data/db.sqlite3"